// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// InsertEmployee mocks base method.
func (m *MockUserRepositoryInterface) InsertEmployee(arg0 InsertEmployeeRequest) (InsertEmployeeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEmployee", arg0)
	ret0, _ := ret[0].(InsertEmployeeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEmployee indicates an expected call of InsertEmployee.
func (mr *MockUserRepositoryInterfaceMockRecorder) InsertEmployee(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmployee", reflect.TypeOf((*MockUserRepositoryInterface)(nil).InsertEmployee), arg0)
}

// InsertFamilies mocks base method.
func (m *MockUserRepositoryInterface) InsertFamilies(arg0 InsertFamiliesDataRequest) (InsertFamiliesDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFamilies", arg0)
	ret0, _ := ret[0].(InsertFamiliesDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertFamilies indicates an expected call of InsertFamilies.
func (mr *MockUserRepositoryInterfaceMockRecorder) InsertFamilies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFamilies", reflect.TypeOf((*MockUserRepositoryInterface)(nil).InsertFamilies), arg0)
}
